# Generated by Django 6.0.3 on 2026-04-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="avg_order_value",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="total_returns",
            field=models.FloatField(default=0),
        ),
    ]
