# Generated by Django 6.0.4 on 2026-04-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_company_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvupload",
            name="source_file",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/%Y/%m/%d/"
            ),
        ),
    ]
