# Generated by Django 6.0.4 on 2026-04-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_csvupload_source_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="confidence",
            field=models.CharField(
                choices=[("high", "High"), ("moderate", "Moderate"), ("low", "Low")],
                default="high",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="missing_features",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
